export const imgUrl = 'www.smartweb.dz/images/domains-img-1.png,' +
    'www.smartweb.dz/images/icons/favicon.png,' +
    'www.smartweb.dz/images/icons/d5.png,' +
    'www.smartweb.dz/images/icons/icon-50.png,' +
    'www.smartweb.dz/images/icons/lan/ios.png,' +
    'www.smartweb.dz/images/icons/lan/symfony.png,' +
    'www.smartweb.dz/images/icons/lan/prestashop.png,' +
    'www.smartweb.dz/images/icons/lan/drupal.png,' +
    'www.smartweb.dz/images/icons/lan/windows.png,' +
    'www.smartweb.dz/images/icons/lan/icon-cordova.png,' +
    'www.smartweb.dz/images/icons/lan/csharp.png,' +
    'www.smartweb.dz/images/icons/lan/smartbase.png,' +
    'www.smartweb.dz/images/icons/lan/jquery.png,' +
    'www.smartweb.dz/images/icons/lan/wordpress.png,' +
    'www.smartweb.dz/images/icons/lan/azure.png,' +
    'www.smartweb.dz/images/icons/lan/android.png,' +
    'www.smartweb.dz/images/icons/lan/zend.png,' +
    'www.smartweb.dz/images/icons/lan/xamarin.png,' +
    'www.smartweb.dz/images/icons/lan/telerik.png,' +
    'www.smartweb.dz/images/icons/lan/dotnet.png,' +
    'www.smartweb.dz/images/icons/lan/mysql.png,' +
    'www.smartweb.dz/images/icons/lan/html-css.png,' +
    'www.smartweb.dz/images/icons/lan/sql_server.png,' +
    'www.smartweb.dz/images/icons/lan/joomla.png,' +
    'www.smartweb.dz/images/icons/lan/php.png,' +
    'www.smartweb.dz/images/icons/icon-52.png,' +
    'www.smartweb.dz/images/icons/b2.png,' +
    'www.smartweb.dz/images/icons/b4.png,' +
    'www.smartweb.dz/images/icons/d2.png,' +
    'www.smartweb.dz/images/icons/d3.png,' +
    'www.smartweb.dz/images/icons/b1.png,' +
    'www.smartweb.dz/images/icons/d1.png,' +
    'www.smartweb.dz/images/icons/b6.png,' +
    'www.smartweb.dz/images/icons/b5.png,' +
    'www.smartweb.dz/images/icons/b3.png,' +
    'www.smartweb.dz/images/icons/icon-51.png,' +
    'www.smartweb.dz/images/icons/d4.png,' +
    'www.smartweb.dz/images/icons/comparatif.png,' +
    'www.smartweb.dz/images/icons/d6.png,' +
    'www.smartweb.dz/images/social/youtube.png,' +
    'www.smartweb.dz/images/social/twitter.png,' +
    'www.smartweb.dz/images/social/google.png,' +
    'www.smartweb.dz/images/social/facebook.png,' +
    'www.smartweb.dz/images/cms/prestashop.png,' +
    'www.smartweb.dz/images/cms/drupal.png,' +
    'www.smartweb.dz/images/cms/magento.png,' +
    'www.smartweb.dz/images/cms/shopify.png,' +
    'www.smartweb.dz/images/cms/wordpress.png,' +
    'www.smartweb.dz/images/cms/opencart.png,' +
    'www.smartweb.dz/images/cms/joomla.png,' +
    'www.smartweb.dz/images/services/mobile/accompagnement.jpg' +
    'www.smartweb.dz/images/services/mobile/intro.jpg' +
    'www.smartweb.dz/images/services/mobile/deployment.png,' +
    'www.smartweb.dz/images/services/mobile/clear-mobile-apps.jpg' +
    'www.smartweb.dz/images/services/mobile/mobile-app.jpg' +
    'www.smartweb.dz/images/services/mobile/custom-mobile-apps.jpg' +
    'www.smartweb.dz/images/services/mobile/gadgets.png,' +
    'www.smartweb.dz/images/services/refonte/intro.png,' +
    'www.smartweb.dz/images/services/refonte/responsive.jpg' +
    'www.smartweb.dz/images/services/refonte/clean-website.jpg' +
    'www.smartweb.dz/images/services/refonte/refonte-siteweb.jpg' +
    'www.smartweb.dz/images/services/refonte/cms.png,' +
    'www.smartweb.dz/images/services/refonte/programmation-solide.jpg' +
    'www.smartweb.dz/images/services/design/web-design.jpg' +
    'www.smartweb.dz/images/services/design/design-smartweb-02.png,' +
    'www.smartweb.dz/images/services/design/custom-design.png,' +
    'www.smartweb.dz/images/services/design/high-quality-design.jpg' +
    'www.smartweb.dz/images/services/design/design-smartweb-01.png,' +
    'www.smartweb.dz/images/services/design/communication-digital.png,' +
    'www.smartweb.dz/images/services/design/responsive-design.jpg' +
    'www.smartweb.dz/images/services/graphique/visit-card.jpg' +
    'www.smartweb.dz/images/services/graphique/flyer.jpg' +
    'www.smartweb.dz/images/services/graphique/brand.jpg' +
    'www.smartweb.dz/images/services/graphique/graphic.jpg' +
    'www.smartweb.dz/images/services/graphique/graphique.jpg' +
    'www.smartweb.dz/images/services/graphique/brand-logo.jpg' +
    'www.smartweb.dz/images/services/publicites/intro.png,' +
    'www.smartweb.dz/images/services/publicites/team.jpg' +
    'www.smartweb.dz/images/services/publicites/google-adwords.png,' +
    'www.smartweb.dz/images/services/publicites/publicites-en-ligne.jpg' +
    'www.smartweb.dz/images/services/publicites/linkedin.png,' +
    'www.smartweb.dz/images/services/publicites/social-media.jpg' +
    'www.smartweb.dz/images/services/publicites/google-partner.jpg' +
    'www.smartweb.dz/images/services/publicites/facebook.png,' +
    'www.smartweb.dz/images/services/consulting/objectif-consulting.png,' +
    'www.smartweb.dz/images/services/consulting/analyse.jpg' +
    'www.smartweb.dz/images/services/consulting/intro.jpg' +
    'www.smartweb.dz/images/services/consulting/icon-01.png,' +
    'www.smartweb.dz/images/services/consulting/icon-03.png,' +
    'www.smartweb.dz/images/services/consulting/consulting.jpg' +
    'www.smartweb.dz/images/services/consulting/icon-02.png,' +
    'www.smartweb.dz/images/services/ecommerce/ecommerce-header.jpg' +
    'www.smartweb.dz/images/services/ecommerce/online-payment.jpg' +
    'www.smartweb.dz/images/services/ecommerce/design-fonctionel-02.png,' +
    'www.smartweb.dz/images/services/ecommerce/ecommerce-cart.png,' +
    'www.smartweb.dz/images/services/ecommerce/ecommerce.jpg' +
    'www.smartweb.dz/images/services/ecommerce/ecommerce-intro.png,' +
    'www.smartweb.dz/images/services/referencement/02.png,' +
    'www.smartweb.dz/images/services/referencement/referencement-siteweb.jpg' +
    'www.smartweb.dz/images/services/referencement/intro.jpg' +
    'www.smartweb.dz/images/services/referencement/03.png,' +
    'www.smartweb.dz/images/services/referencement/google-adwords.png,' +
    'www.smartweb.dz/images/services/referencement/01.png,' +
    'www.smartweb.dz/images/services/referencement/04.png,' +
    'www.smartweb.dz/images/services/referencement/social-media.jpg' +
    'www.smartweb.dz/images/vps.png,' +
    'www.smartweb.dz/images/slider/design.jpg' +
    'www.smartweb.dz/images/slider/development.jpg' +
    'www.smartweb.dz/images/slider/hosting.jpg' +
    'www.smartweb.dz/images/slider/play.png,' +
    'www.smartweb.dz/images/slider/play2.jpg' +
    'www.smartweb.dz/images/slider/marketing.jpg' +
    'www.smartweb.dz/images/design/clock_icon.png,' +
    'www.smartweb.dz/images/design/support2.png,' +
    'www.smartweb.dz/images/partners/cisco.png,' +
    'www.smartweb.dz/images/partners/juniper.png,' +
    'www.smartweb.dz/images/partners/comodo.png,' +
    'www.smartweb.dz/images/partners/netapp.png,' +
    'www.smartweb.dz/images/partners/icann.png,' +
    'www.smartweb.dz/images/partners/verisign.png,' +
    'www.smartweb.dz/images/partners/ibm.png,' +
    'www.smartweb.dz/images/partners/hubspot.png,' +
    'www.smartweb.dz/images/partners/centos.png,' +
    'www.smartweb.dz/images/partners/vmware.png,' +
    'www.smartweb.dz/images/icn/about-icon-11.png,' +
    'www.smartweb.dz/images/icn/em01.png,' +
    'www.smartweb.dz/images/icn/em04.png,' +
    'www.smartweb.dz/images/icn/pub.png,' +
    'www.smartweb.dz/images/icn/about-icon-09.png,' +
    'www.smartweb.dz/images/icn/sl01.png,' +
    'www.smartweb.dz/images/icn/empro03.png,' +
    'www.smartweb.dz/images/icn/domain.png,' +
    'www.smartweb.dz/images/icn/srv04.png,' +
    'www.smartweb.dz/images/icn/refonte.png,' +
    'www.smartweb.dz/images/icn/shared.png,' +
    'www.smartweb.dz/images/icn/email.png,' +
    'www.smartweb.dz/images/icn/support-01.png,' +
    'www.smartweb.dz/images/icn/graphic-design.png,' +
    'www.smartweb.dz/images/icn/web-design.png,' +
    'www.smartweb.dz/images/icn/empro02.png,' +
    'www.smartweb.dz/images/icn/managedServer.png,' +
    'www.smartweb.dz/images/icn/srv05.png,' +
    'www.smartweb.dz/images/icn/about-icon-04.png,' +
    'www.smartweb.dz/images/icn/vps.png,' +
    'www.smartweb.dz/images/icn/sl03.png,' +
    'www.smartweb.dz/images/icn/em02.png,' +
    'www.smartweb.dz/images/icn/ms03.png,' +
    'www.smartweb.dz/images/icn/emailpro.png,' +
    'www.smartweb.dz/images/icn/sl02.png,' +
    'www.smartweb.dz/images/icn/about-icon-10.png,' +
    'www.smartweb.dz/images/icn/about-icon-12.png,' +
    'www.smartweb.dz/images/icn/ms02.png,' +
    'www.smartweb.dz/images/icn/ecommerce.png,' +
    'www.smartweb.dz/images/icn/about-icon-05.png,' +
    'www.smartweb.dz/images/icn/websecurity.png,' +
    'www.smartweb.dz/images/icn/consulting.png,' +
    'www.smartweb.dz/images/icn/about-icon-08.png,' +
    'www.smartweb.dz/images/icn/srv07.png,' +
    'www.smartweb.dz/images/icn/dev-mobile.png,' +
    'www.smartweb.dz/images/icn/about-icon-13.png,' +
    'www.smartweb.dz/images/icn/em06.png,' +
    'www.smartweb.dz/images/icn/about-icon-03.png,' +
    'www.smartweb.dz/images/icn/ms05.png,' +
    'www.smartweb.dz/images/icn/dedicatedServer.png,' +
    'www.smartweb.dz/images/icn/em05.png,' +
    'www.smartweb.dz/images/icn/ms06.png,' +
    'www.smartweb.dz/images/icn/about-icon-02.png,' +
    'www.smartweb.dz/images/icn/ms04.png,' +
    'www.smartweb.dz/images/icn/em03.png,' +
    'www.smartweb.dz/images/icn/about-icon-01.png,' +
    'www.smartweb.dz/images/icn/support-03.png,' +
    'www.smartweb.dz/images/icn/srv03.png,' +
    'www.smartweb.dz/images/icn/ms01.png,' +
    'www.smartweb.dz/images/icn/srv06.png,' +
    'www.smartweb.dz/images/icn/empro04.png,' +
    'www.smartweb.dz/images/icn/about-icon-07.png,' +
    'www.smartweb.dz/images/icn/empro05.png,' +
    'www.smartweb.dz/images/icn/empro01.png,' +
    'www.smartweb.dz/images/icn/support-02.png,' +
    'www.smartweb.dz/images/icn/srv08.png,' +
    'www.smartweb.dz/images/icn/about-icon-06.png,' +
    'www.smartweb.dz/images/icn/empro06.png,' +
    'www.smartweb.dz/images/icn/seo.png,' +
    'www.smartweb.dz/images/patterns/2.png,' +
    'www.smartweb.dz/images/patterns/11.png,' +
    'www.smartweb.dz/images/softwares/mozilla-thunderbird.png,' +
    'www.smartweb.dz/images/softwares/kompozer.png,' +
    'www.smartweb.dz/images/softwares/inscape.png,' +
    'www.smartweb.dz/images/softwares/open-office.png,' +
    'www.smartweb.dz/images/softwares/gimp.png,' +
    'www.smartweb.dz/images/softwares/mozilla-firefox.png,' +
    'www.smartweb.dz/images/softwares/filezilla.png,' +
    'www.smartweb.dz/images/softwares/keypass.png,' +
    'www.smartweb.dz/images/softwares/7zip.png,' +
    'www.smartweb.dz/images/bg/sitelock.png,' +
    'www.smartweb.dz/images/bg/ssl.png,' +
    'www.smartweb.dz/images/payment.png,' +
    'www.smartweb.dz/images/logo-smartweb.png,' +
    'www.smartweb.dz/images/bgi/contact.jpg' +
    'www.smartweb.dz/images/bgi/recrutement-smartweb.jpg' +
    'www.smartweb.dz/images/bgi/vps3.jpg' +
    'www.smartweb.dz/images/bgi/browser.png,' +
    'www.smartweb.dz/images/bgi/comodo-ssl.png,' +
    'www.smartweb.dz/images/bgi/cpanel.png,' +
    'www.smartweb.dz/images/bgi/af04.png,' +
    'www.smartweb.dz/images/bgi/managedServer.jpg' +
    'www.smartweb.dz/images/bgi/about-smartweb-01.jpg' +
    'www.smartweb.dz/images/bgi/logiciels-utiles.jpg' +
    'www.smartweb.dz/images/bgi/about-us.jpg' +
    'www.smartweb.dz/images/bgi/dedicated.jpg' +
    'www.smartweb.dz/images/bgi/team.jpg' +
    'www.smartweb.dz/images/bgi/domain.jpg' +
    'www.smartweb.dz/images/bgi/devis.jpg' +
    'www.smartweb.dz/images/bgi/security.jpg' +
    'www.smartweb.dz/images/bgi/ebusiness.jpg' +
    'www.smartweb.dz/images/bgi/emailpro-idea.png,' +
    'www.smartweb.dz/images/bgi/emailpro-partners.png,' +
    'www.smartweb.dz/images/bgi/grey-bg.jpg' +
    'www.smartweb.dz/images/bgi/dedicated2.png,' +
    'www.smartweb.dz/images/bgi/email.jpg' +
    'www.smartweb.dz/images/bgi/whois.jpg' +
    'www.smartweb.dz/images/bgi/job2.png,' +
    'www.smartweb.dz/images/bgi/securemail.png,' +
    'www.smartweb.dz/images/bgi/emailpro-security.png,' +
    'www.smartweb.dz/images/bgi/af05.png,' +
    'www.smartweb.dz/images/bgi/emailpro-sync.png,' +
    'www.smartweb.dz/images/bgi/anti-ddos.png,' +
    'www.smartweb.dz/images/bgi/https.png,' +
    'www.smartweb.dz/images/bgi/smartweb-technologies.png,' +
    'www.smartweb.dz/images/bgi/patern-01.jpg' +
    'www.smartweb.dz/images/bgi/sharedHosting.jpg' +
    'www.smartweb.dz/images/bgi/affiliate.jpg' +
    'www.smartweb.dz/images/bgi/emailpro.jpg' +
    'www.smartweb.dz/images/bgi/satisfaction.png,' +
    'www.smartweb.dz/images/bgi/meeting.png,' +
    'www.smartweb.dz/images/bgi/dedicated-monitoring.png,' +
    'www.smartweb.dz/images/bgi/tutoriels-smartweb.jpg' +
    'www.smartweb.dz/images/bgi/intel-xeon.png,' +
    'www.smartweb.dz/images/bgi/cloudMail.png';