export const amplishopUrl = 'amplishop.com/wp-content/plugins/ninja-forms/deprecated/images/star.gif,' +
'amplishop.com/wp-content/plugins/ninja-forms/deprecated/images/delete.gif,' +
'amplishop.com/wp-content/plugins/lc-googlemaps/images/map-placeholder.png,' +
'amplishop.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/common/loading-2.gif,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/common/grab.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/common/video-close-btn.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/common/grabbing.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/templates/device-skin.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/templates/gallery-btns.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/templates/vertical-arrows.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/templates/staff-arrows.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/metro-skin-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-6-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-4.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-2.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-5.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/metro-skin.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-3-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-1-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/black-skin-1.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-2-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-6.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/black-skin-1-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-5-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/contrast-skin-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/black-skin-2-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-4-retina.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-3.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/contrast-skin.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/light-skin-1.png,' +
'amplishop.com/wp-content/plugins/masterslider/public/assets/css/skins/black-skin-2.png,' +
'amplishop.com/wp-content/themes/assiaboost-seowp/images/select_arrow.png,' +
'amplishop.com/design/design/images/seo-wordpress-theme-logo-horizontal.png,' +
'amplishop.com/design/images/preloader.gif,' +
'amplishop.com/agencewebnantes/img/l/1.jpg,' +
'amplishop.com/agencewebnantes/img/loader.gif,' +
'amplishop.com/agencewebnantes/img/leoblog/b/22/690_300/b-blog-6.jpg,' +
'amplishop.com/agencewebnantes/img/leoblog/b/21/690_300/b-blog-5.jpg,' +
'amplishop.com/agencewebnantes/img/leoblog/b/23/690_300/b-blog-7.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg_table_th.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/icon-search-white.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg-404.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/icon/form-ok.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/icon/form-error.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/icon/delete.gif,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg-title-left.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg_input.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bankwire.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/arow-down.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/patterns/full-screen/style-1.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/patterns/full-screen/style-2.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/patterns/full-screen/style-3.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/cash.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/cheque.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg-title-right.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/leobootstrapmenu/icons/agenceweb.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/,' +
    'agence_web_comunication_nantes_creation_site_ecommerce2.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/icon-free-shipping.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/icon-custom-service.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/img-block-dreams.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/,' +
    'agence_web_comunication_nantes_creation_site_vitrine_presentation.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/avatar-1.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/icon-secury-checkout.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/modules/appagebuilder/images/avatar-2.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/img-404.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/bg-free-shipping-home-3.jpg,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/img/icon-subcrible-letter.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/css/modules/appagebuilder/views/img/grabbing.png,' +
'amplishop.com/agencewebnantes/themes/leo_mayshop/css/modules/appagebuilder/views/img/AjaxLoader.gif,' +
'amplishop.com/agencewebnantes/modules/paypal/views/img/sprites.png,' +
'amplishop.com/agencewebnantes/modules/paypal/views/img/bg-call-button.png,' +
'amplishop.com/agencewebnantes/modules/paypal/views/img/bg-button.png,' +
'amplishop.com/agencewebnantes/modules/paypal/views/img/blue_tick.png,' +
'amplishop.com/agencewebnantes/modules/productcomments/img/delete.gif,' +
    'amplishop.com/agencewebnantes/modules/blockpermanentlinks/img/arrow_right_2.png,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/fancybox_loading@2x.gif,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/fancybox_sprite@2x.png,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/fancybox_loading.gif,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/blank.gif,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/fancybox_sprite.png,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/fancybox/fancybox_overlay.png,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/bxslider/images/controls.png,' +
'amplishop.com/agencewebnantes/js/jquery/plugins/bxslider/images/bx_loader.gif,' +
'amplishop.com/webagency/plugins/masterslider/public/assets/css/blank.gif,' +
'amplishop.com/telechargements/services-seo-copyrighting-300x300.png,' +
'amplishop.com/telechargements/creation-site-internet-vitrine-responsive-agence-web-paris-389x260.png,' +
'amplishop.com/telechargements/creation-site-ecommerce-agence-web-paris.png,' +
'amplishop.com/telechargements/avatar-7.png,' +
'amplishop.com/telechargements/avatar-6.png,' +
'amplishop.com/telechargements/services-afilate-management-380x380.png,' +
'amplishop.com/telechargements/pattern-web-ransparent.png,' +
'amplishop.com/telechargements/services-seo-copyrighting-400x400.png,' +
'amplishop.com/telechargements/services-conversion-rate-optimization-380x380.png,' +
'amplishop.com/telechargements/services-payperclick-380x380.png,' +
'amplishop.com/telechargements/services-webdesign-optimized.png,' +
'amplishop.com/telechargements/services-strategy-on-light-440x440.png,' +
'amplishop.com/telechargements/services-payperclick-optimized.png,' +
'amplishop.com/telechargements/avatar-2.png,' +
'amplishop.com/telechargements/services-local-seo-381x381.png,' +
'amplishop.com/telechargements/seo_specialist_workplace-optimized.png,' +
'amplishop.com/telechargements/pattern-shattered-transparent-contrast-low.png,' +
'amplishop.com/telechargements/services-prize-on-light-440x440.png,' +
'amplishop.com/telechargements/avatar-5.png,' +
'amplishop.com/telechargements/seo-wordpress-theme-logo-vertical-gray-on-dark@2x-160x153.png,' +
'amplishop.com/telechargements/avatar-4.png,' +
'amplishop.com/telechargements/avatar-1.png,' +
'amplishop.com/telechargements/services-digital-consultancy-380x380.png,' +
'amplishop.com/telechargements/services-seo-alt-colors-optimized.png,' +
'amplishop.com/telechargements/avatar-3.png,' +
'amplishop.com/telechargements/services-search-engine-optimization-380x380.png,' +
'amplishop.com/telechargements/services-socialmediamarketing-alt-colors-optimized-340x340.png,' +
'amplishop.com/telechargements/services-payperclick-alt-colors-optimized.png,' +
'amplishop.com/telechargements/services-web-design-380x380.png,' +
'amplishop.com/telechargements/creation-site-internet-vitrine-responsive-agence-web-paris.png,' +
'amplishop.com/telechargements/services-marketingresearch-optimized.png,' +
'amplishop.com/telechargements/creation-site-ecommerce-responsive.png,' +
'amplishop.com/telechargements/creation-site-internet-vitrine-responsive-agence-web.png,' +
'amplishop.com/telechargements/services-seo-copyrighting-420x420.png,' +
'amplishop.com/telechargements/services-socialmediamarketing-alt-colors-optimized.png,' +
'amplishop.com/telechargements/services-local-seo-services-on-light-440x440.png,' +
'amplishop.com/telechargements/services-seo-optimized.png,' +
'amplishop.com/telechargements/avatar-8.png,' +
'amplishop.com/telechargements/services-mobile-marketing-380x380.png,' +
'amplishop.com/telechargements/ryte.png,' +
'amplishop.com/telechargements/illustration-mission-optimized-300x300.png,' +
'amplishop.com/telechargements/services-analytics-alt-colors-optimized-300x300.png,' +
'amplishop.com/telechargements/ryte-300x99.png,' +
'amplishop.com/telechargements/services-analytics-alt-colors-optimized.png,' +
'amplishop.com/telechargements/services-web-services-on-light-340x340.png,' +
'amplishop.com/telechargements/seowp-dropdown-bg-300x89.png,' +
'amplishop.com/telechargements/services-content-strategy-380x380.png,' +
'amplishop.com/telechargements/creation-site-ecommerce-agence-web-paris-389x260.png,' +
'amplishop.com/telechargements/services-prize-on-light-380x380.png,' +
'amplishop.com/telechargements/creation-site-ecommerce-responsive-agence-web-2.png,' +
'amplishop.com/telechargements/services-email-marketing-380x380.png';